/*
Copyright The Flagger Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/weaveworks/flagger/pkg/apis/flagger/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCanaryFilters implements CanaryFilterInterface
type FakeCanaryFilters struct {
	Fake *FakeFlaggerV1beta1
	ns   string
}

var canaryfiltersResource = schema.GroupVersionResource{Group: "flagger.app", Version: "v1beta1", Resource: "canaryfilters"}

var canaryfiltersKind = schema.GroupVersionKind{Group: "flagger.app", Version: "v1beta1", Kind: "CanaryFilter"}

// Get takes name of the canaryFilter, and returns the corresponding canaryFilter object, and an error if there is any.
func (c *FakeCanaryFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.CanaryFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(canaryfiltersResource, c.ns, name), &v1beta1.CanaryFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CanaryFilter), err
}

// List takes label and field selectors, and returns the list of CanaryFilters that match those selectors.
func (c *FakeCanaryFilters) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.CanaryFilterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(canaryfiltersResource, canaryfiltersKind, c.ns, opts), &v1beta1.CanaryFilterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.CanaryFilterList{ListMeta: obj.(*v1beta1.CanaryFilterList).ListMeta}
	for _, item := range obj.(*v1beta1.CanaryFilterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested canaryFilters.
func (c *FakeCanaryFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(canaryfiltersResource, c.ns, opts))

}

// Create takes the representation of a canaryFilter and creates it.  Returns the server's representation of the canaryFilter, and an error, if there is any.
func (c *FakeCanaryFilters) Create(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.CreateOptions) (result *v1beta1.CanaryFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(canaryfiltersResource, c.ns, canaryFilter), &v1beta1.CanaryFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CanaryFilter), err
}

// Update takes the representation of a canaryFilter and updates it. Returns the server's representation of the canaryFilter, and an error, if there is any.
func (c *FakeCanaryFilters) Update(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.UpdateOptions) (result *v1beta1.CanaryFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(canaryfiltersResource, c.ns, canaryFilter), &v1beta1.CanaryFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CanaryFilter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCanaryFilters) UpdateStatus(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.UpdateOptions) (*v1beta1.CanaryFilter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(canaryfiltersResource, "status", c.ns, canaryFilter), &v1beta1.CanaryFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CanaryFilter), err
}

// Delete takes name of the canaryFilter and deletes it. Returns an error if one occurs.
func (c *FakeCanaryFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(canaryfiltersResource, c.ns, name), &v1beta1.CanaryFilter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCanaryFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(canaryfiltersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.CanaryFilterList{})
	return err
}

// Patch applies the patch and returns the patched canaryFilter.
func (c *FakeCanaryFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CanaryFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(canaryfiltersResource, c.ns, name, pt, data, subresources...), &v1beta1.CanaryFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CanaryFilter), err
}
