/*
Copyright The Flagger Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/weaveworks/flagger/pkg/apis/flagger/v1beta1"
	scheme "github.com/weaveworks/flagger/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CanaryFiltersGetter has a method to return a CanaryFilterInterface.
// A group's client should implement this interface.
type CanaryFiltersGetter interface {
	CanaryFilters(namespace string) CanaryFilterInterface
}

// CanaryFilterInterface has methods to work with CanaryFilter resources.
type CanaryFilterInterface interface {
	Create(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.CreateOptions) (*v1beta1.CanaryFilter, error)
	Update(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.UpdateOptions) (*v1beta1.CanaryFilter, error)
	UpdateStatus(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.UpdateOptions) (*v1beta1.CanaryFilter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.CanaryFilter, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.CanaryFilterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CanaryFilter, err error)
	CanaryFilterExpansion
}

// canaryFilters implements CanaryFilterInterface
type canaryFilters struct {
	client rest.Interface
	ns     string
}

// newCanaryFilters returns a CanaryFilters
func newCanaryFilters(c *FlaggerV1beta1Client, namespace string) *canaryFilters {
	return &canaryFilters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the canaryFilter, and returns the corresponding canaryFilter object, and an error if there is any.
func (c *canaryFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.CanaryFilter, err error) {
	result = &v1beta1.CanaryFilter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("canaryfilters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CanaryFilters that match those selectors.
func (c *canaryFilters) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.CanaryFilterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.CanaryFilterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("canaryfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested canaryFilters.
func (c *canaryFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("canaryfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a canaryFilter and creates it.  Returns the server's representation of the canaryFilter, and an error, if there is any.
func (c *canaryFilters) Create(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.CreateOptions) (result *v1beta1.CanaryFilter, err error) {
	result = &v1beta1.CanaryFilter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("canaryfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(canaryFilter).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a canaryFilter and updates it. Returns the server's representation of the canaryFilter, and an error, if there is any.
func (c *canaryFilters) Update(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.UpdateOptions) (result *v1beta1.CanaryFilter, err error) {
	result = &v1beta1.CanaryFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("canaryfilters").
		Name(canaryFilter.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(canaryFilter).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *canaryFilters) UpdateStatus(ctx context.Context, canaryFilter *v1beta1.CanaryFilter, opts v1.UpdateOptions) (result *v1beta1.CanaryFilter, err error) {
	result = &v1beta1.CanaryFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("canaryfilters").
		Name(canaryFilter.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(canaryFilter).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the canaryFilter and deletes it. Returns an error if one occurs.
func (c *canaryFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("canaryfilters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *canaryFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("canaryfilters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched canaryFilter.
func (c *canaryFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CanaryFilter, err error) {
	result = &v1beta1.CanaryFilter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("canaryfilters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
